### ISSUE TITLE
RepeatClassifier custom -num_threads

### ISSUE THREAD

**Issue by cascoamarillo** [Dfam-consortium/RepeatModeler#112]
Hi,

I have been running RepeatClassifier alone for custom TE library classification. I see in the new version (RepeatModeler2) there is the option for number of threads to use:
```
419 my $additionalOpts = "";
420  $additionalOpts = "-num_threads $options{'pa'} " if ( $options{'pa'} );
```

but when I used "-pa" (eg. -pa 12)  there is no extra use of threads in the cluster. It's quite limiting for a large TE library, specially the blastx step which uses only 1 cpu, and then rmblastn apparently is able to use 4 cpu's? I am wondering if it can be optimized for a specific cluster with some extra room for processing. Thank you.

**Comment by rmhubley** [comment]
Sorry for the delayed response.  As you have noted blastx doesn't appear to benefit from having the "-num_threads #" parameter specified.  I haven't looked into the blastx code at all so it's unclear to me why a multiple query/multiple subject search couldn't be internally parallelized.  Unfortunately, in order to fix this we will need to breakup the input files and run multiple blastx jobs in heavy-weight processes.  This may be solved when we move to a job-based approach to support clusters in the near future.

**Comment by cascoamarillo** [comment]
Thanks for the heads up.
Closing.
