### ISSUE TITLE
My <dataset.fa.out> is mostly simple repeats and low complexity rather than TE families, is that normal?

### ISSUE THREAD

**Issue by xyz0o** [Dfam-consortium/RepeatModeler#117]
Hi,

I have installed the Rmodeler2 singularity container and I have merged the RepBase library to the RMasker library which is integrated inside the container using below instruction:
```
# Navigate to an appropriate directory that is persistent outside the container
$ cd /work

# Make a copy of RepeatMasker's Libraries directory here
$ cp -r /opt/RepeatMasker/Libraries/ ./

# Extract RepBase (the .tar.gz file unpacks files into Libraries/)
$ tar -x -f /work/path/to/RepBaseRepeatMaskerEdition-#######.tar.gz

# Run the 'addRepBase.pl' script (part of the RepeatMasker package) to merge the databases,
# specifying the custom Libraries directory.
$ addRepBase.pl -libdir Libraries/

# Run RepeatMasker with the LIBDIR environment variable set
$ export LIBDIR=/path/to/Libraries

```
I have run the Repeatmodeler on a non-model organism's genome assembly:
`singularity exec --bind $PWD:$PWD ./tetools.sif  RepeatModeler  -database monCan3F9 -pa 40 -LTRStruct` 

then I masked it on the custom library:
`singularity exec --bind $PWD:$PWD ./tetools.sif RepeatMasker -lib monCan3F9-families.fa monCan3F9.fa -engine ncbi -pa 40
`
my output file is mostly mostly simple repeats and low complexity rather than TE families, is that normal?
![session](https://user-images.githubusercontent.com/77616805/106474561-b4c71d80-64ad-11eb-994b-cecd014acfef.jpg)

**Comment by jebrosen** [comment]
> my output file is mostly mostly simple repeats and low complexity rather than TE families, is that normal?

What does the summary file (`.tbl`) say? There are several reasons you might see this:

* The genome itself (or the specific contig in your screenshot) has more simple repeats and low-complexity regions than it does TE families.
* This specific assembly of the genome is poor in regions that contain repeats, and some repeats did not actually get assembled. Repeats, especially the ones with a high number of copies, are simply difficult to assemble (depending a bit on the sequencing and assembly technologies used).
* Some of the identified models are fragments of full-length TE families and might be further extened based on more evidence in the genome. This might happen if the signal is not strong enough for RepeatModeler or one of its components to have called or extended the family, but with human guidance or different cutoffs it could be.

---

I'm also going to try and answer Dfam-consortium/TETools#7 here, since it doesn't seem to be a problem with the TE Tools container itself. I think this also answers #116?

> now before running the RepeatMasker, I want to merge the monCan3F9-families.fa with the "Dfam.h5" library, how should I do that?
>
> Also, regarding your new RM version, should I utilize the "queryRepeatDatabase" option to separately drag Drosophila library or not? because I saw it in older versions of RM but couldn't find in your current documentation with the container.

For a general approach, see the first part of this answer: https://github.com/Dfam-consortium/RepeatModeler/issues/40#issuecomment-527565134

In particular, it sounds like you are asking about this:

> (...) we recommend that the the output of RepeatModeler combined with already defined repeats ( RepeatMasker/util/queryRepeatDatabase -species ... ) be placed into a custom library and then run through RepeatMasker with the "-lib" option.

`queryRepeatDatabase` was replaced with `famdb.py`. To extract a species-specific FASTA library from the installed libraries, you can run this command while inside your `Libraries` directory:
`famdb.py -i RepeatMaskerLib.h5 families --format fasta_name  --include-class-in-name --ancestors --descendants 'species name' >species-rm.fa`

Then, the files can be combined with `cat`: `cat species-rm.fa monCan3F9-families.fa > monCan3F9-combined.fa`. The resulting `monCan3F9-combined.fa` file can be used with RepeatMasker's `-lib` option.

---

I hope this answers your questions!

**Comment by xyz0o** [comment]
Thanks for answering my both questions, 

well since my genome assembly is of long-read sequences my guess is that because I didn't combine the libraries before makisng it,  many of he repeats are not masked on a specific TE. 

I tried the above command with `famdb.py -i RepeatMaskerLib.h5 names  drosophila > drosophila.rm.fa` also with ( 'lineage', and 'families')  but each time I receive the same message:

> Ambiguous search term 'drosophila' (found 989 results, 2 exact).
> Please use a more specific name or taxa ID, which can be looked
> up with the 'names' command.

can't I have all of the drosophila species in a single fasta file?

**Comment by jebrosen** [comment]
Here is what I get with the `names` command. Drosophila is the name of both a genus and a related subgenus:

```
./famdb.py -i Libraries/RepeatMaskerLib.h5 names drosophila | head
Exact Matches
=============
32281 Drosophila <flies,subgenus> (scientific name), Drosophila (Drosophila) (includes), Drosophila (Drosophila) Fallen, 1823 (authority)
7215 Drosophila <flies,genus> (scientific name), Drosophila Fallen, 1823 (authority), fruit flies <Drosophila> (genbank common name), fruit fly <Drosophila> (common name)
```

You can specify the Drosophila flies genus, by using the ID `7215` instead of the word `drosophila` in the command. Maybe we can hardcode `drosophila` to mean the genus, because it's a very commonly used term.

**Comment by xyz0o** [comment]
so, basically, what is in my drosophila.rm.fa file is only this single line:

```
Exact Matches
=============
7215 Drosophila <flies,genus> (scientific name), Drosophila Fallen, 1823 (authority), fruit flies <Drosophila> (genbank common name), fruit fly <Drosophila> (common name)

```
is that correct?
also when I combine the libraries and run the repeatmasker, I receive this error:

```
RepeatMasker version 4.1.1
Search Engine: NCBI/RMBLAST [ 2.10.0+ ]
Using Custom Repeat Library: monCan3F9-combined.fa

Building general libraries in: /users/tahamimo/.RepeatMaskerCache//general
RepeatMasker::createLib(): Error invoking /opt/rmblast/bin/makeblastdb on file /users/tahamimo/.RepeatMaskerCache//general/is.lib.
```

I haven't had this error before, I don't what I should do?

**Comment by xyz0o** [comment]
> so, basically, what is in my drosophila.rm.fa file is only this single line:
> 
> ```
> Exact Matches
> =============
> 7215 Drosophila <flies,genus> (scientific name), Drosophila Fallen, 1823 (authority), fruit flies <Drosophila> (genbank common name), fruit fly <Drosophila> (common name)
> ```
> 
> is that correct? cause I would expect sequences...
> when I run the repeatmasker with the combined lib, I receive this error:
> 
> ```
> RepeatMasker version 4.1.1
> Search Engine: NCBI/RMBLAST [ 2.10.0+ ]
> RepeatMasker::setspecies: Could not find user specified library monCan3F9-combined.fa, or the file is empty.
> ```
> 
> I have put the monCan3F9-combined.fa lib in the$LIBDIR path so this shouldn't be the problem, the combined file includes all the Repeatmodeler sequences plus the single line generated for dorosphila library on top! I think the problem is this line which technically should be sequences, right?

ok I think my library path is also somehow messed up, when I tried the Rmasker with the output of Rmodeler just as a test:
```
RepeatMasker version 4.1.1
Search Engine: NCBI/RMBLAST [ 2.10.0+ ]
Using Custom Repeat Library: monCan3F9-families.fa

Building general libraries in: /users/tahamimo/.RepeatMaskerCache//general
RepeatMasker::createLib(): Error invoking /opt/rmblast/bin/makeblastdb on file /users/tahamimo/.RepeatMaskerCache//general/is.lib.

```
I tried to re-path the library inside the shell, still the same error
![capture1](https://user-images.githubusercontent.com/77616805/106868947-0d79fe80-66d8-11eb-9c99-e69580424379.jpg)

**Comment by jebrosen** [comment]
> is that correct? cause I would expect sequences...

No, this is the command you need to run:
`famdb.py -i RepeatMaskerLib.h5 families --format fasta_name --include-class-in-name --ancestors --descendants 7215 >species-rm.fa`

The `names` command was a response to this error, to show how you can get an unambiguous taxonomy ID since there is more than one taxon named `drosophila`:
> Ambiguous search term 'drosophila' (found 989 results, 2 exact).
> Please use a more specific name or taxa ID, which can be looked
> up with the 'names' command.

---

`RepeatMasker::createLib(): Error invoking /opt/rmblast/bin/makeblastdb on file /users/tahamimo/.RepeatMaskerCache//general/is.lib.`

Can you paste here the contents of the file `/users/tahamimo/.RepeatMaskerCache/general/rmblastdb.log`, which should include in the underlying error?

**Comment by xyz0o** [comment]
thanks for elaborating on the command for extracting dataset from the lib.

I couldn't find such a path in my host dir, I think something was messed up with my Paths so I removed the image and re-installed from scratch and this time everything is running fine and smoothly, that's the privilege of having containers! :D
