### ISSUE TITLE
"RepeatScout did not return any models" because nseg is missing in RepModelConfig.pm

### ISSUE THREAD

**Issue by xiaoyezao** [Dfam-consortium/RepeatModeler#125]
I modified `RepModelConfig.pm` to set the tool paths (I cannot run the configure because of Perl module issues). There are no lines for the tool nseg in RepModelConfig.pm, and RepeatModeler does not check the availability of nseg, however, this will result in `RepeatScout did not return any models` in round-1. RepeatScout (specifically filter-stage-1.prl) will filter out all identified repeats if nseg is not available without error message. In such case, RepeatModeler seems can finish the job smoothly without results from round-1. Will some repeats are missing in such a run?

**Comment by jebrosen** [comment]
What versions of RepeatModeler and RepeatScout are you using? The most recent releases of RepeatScout and RepeatModeler replaced that usage of `nseg` with `dustmasker`, because `dustmasker` is more actively supported and is already distributed alongside `RMBlast`.

> RepeatScout (specifically filter-stage-1.prl) will filter out all identified repeats if nseg is not available without error message. In such case, RepeatModeler seems can finish the job smoothly without results from round-1. Will some repeats are missing in such a run?

RepeatScout and RECON have different strengths, so it is possible that the results are missing repetitive elements that RepeatScout could find but not RECON. Exactly what kind of difference this has on the final results would depend on the composition of repeats within the particular genome/assembly.

**Comment by xiaoyezao** [comment]
I use RepeatModeler-2.0.1 and RepeatScout-1.0.5 which are both the latest release I think. However, in the round-1 folder of RepeatModeler result, I see `filter-stage-1.log` which is the log file of `filter-stage-1.prl` (RepeatScout script). `filter-stage-1.prl` calls `trf` and `nseg` rather than `dustmaker`. Is there another version of RepeatScout which calls `dustmaker`?

**Comment by jebrosen** [comment]
The latest version of RepeatScout is 1.0.6, linked from the RepeatModeler download page: http://www.repeatmasker.org/RepeatModeler/

**Comment by xiaoyezao** [comment]
Thank you very much!!
