### ISSUE TITLE
RepeatClassifier stops with error missing RepeatMasker.lin.nsq

### ISSUE THREAD

**Issue by Shrihariprasad** [Dfam-consortium/RepeatModeler#137]
**The repeat classifyer stops with an error message stating missing RepeatMasker.lib.nsq**

**Helpful context**

* I was trying to run RepeatModeller for a plant genome and the program ran for 47:50:23 (hh:mm:ss) completing all the 6 rounds
* The RepeatClassifier ran for 42 minutes and ended with an error missing RepeatMasker/libraries/RepeatMasker.lib.nsq please re run the configure program in RepeatModeller directory.
*I tried after re-configuring the program but still the error persists.

* RepeatModeler Version 2.0.1
RepeatMasker version 4.1.1

**Comment by jebrosen** [comment]
> The RepeatClassifier ran for 42 minutes and ended with an error missing RepeatMasker/libraries/RepeatMasker.lib.nsq

42 minutes sounds like the step for comparing the consensi against `RepeatPeps.lib.psq`, which should be generated at the same time and in the same way as `RepeatMasker.lib.nsq`. I'm a bit surprised one of those files was generated but not the other.

> please re run the configure program in RepeatModeller directory.

Sorry about that; this should have said: please re-run the configure program in the **`RepeatMasker`** directory. This message will be fixed in the next release of RepeatModeler.

> RepeatMasker version 4.1.1

This particular version of RepeatMasker is also known to produce some incorrect classifications (see issue #128). Can you try using a version of RepeatMasker without that bug (e.g. RepeatMasker 4.1.0 or RepeatMasker 4.1.2-p2)? If RepeatMasker's `configure` program still does not generate the file `RepeatMasker.lib.nsq`, you can try generating it manually which should explain why it failed:

`.../rmblast/bin/makeblastdb -dbtype nucl -in .../RepeatMasker/Libraries/RepeatMasker.lib`

---

It is not necessary to re-run all of RepeatModeler; RepeatClassifier is the last step. RepeatClassifier can be run separately as follow: `RepeatClassifier -consensi consensi.fa -stockholm families.stk`

**Comment by Shrihariprasad** [comment]
Thank you I tried with the` RepeatMasker version 4.1.2-p1`, reconfigured the RepeatModeller and was able to run RepeatClassifier without errors
 This solved the issue of `RepeatMasker.lib.nsq` issue as well as error #139  [ERROR from search engine (139) sh: line 1: 123072 Segmentation fault (core dumped)]

**Comment by jebrosen** [comment]
Glad to hear that resolved it. Please let us know if you have other issues or questions!
