### ISSUE TITLE
consensi.fa is empty

### ISSUE THREAD

**Issue by 44314474** [Dfam-consortium/RepeatModeler#235]
Hello!
When i used RepeatModeler, the file of consensi.fa is empty, i don't know where is wrong.
The code i used :/home/wei/miniconda3/bin/RepeatModeler -database Callinectes_sapidus -engine ncbi -pa 40
The details:
![1](https://github.com/Dfam-consortium/RepeatModeler/assets/120501819/2bda2b3d-33ae-49e3-81d7-db04376c2fa5)
![image](https://github.com/Dfam-consortium/RepeatModeler/assets/120501819/d427d547-f120-4d1d-927e-3d1184b9042e)
![image](https://github.com/Dfam-consortium/RepeatModeler/assets/120501819/1ed7f85d-6ced-453f-be38-3f38f926b17c)
![image](https://github.com/Dfam-consortium/RepeatModeler/assets/120501819/d492d9a7-bbb2-4bf2-84e1-ba5b839f2b92)
Can you give me some suggestions?
Thanks for your help!

**Comment by Innocent-L** [comment]
Hi, I'm having the same issue, can you solve it? If so, can you tell me the reason for the error？Thanks

**Comment by rmhubley** [comment]
Sorry...for the delay.  There is something very strange with your input genome for this run.  It is atypical that you would have only 5, and consistently 5 instances of a family found by RepeatScout/RECON unless you are handing it a non-standard input sequence.  RepeatModeler has a minimum of 15 instances per family.  All these "discoveries" are being filtered out because of that.
