### ISSUE TITLE
ROUND5  ERROR from search engine (0)

### ISSUE THREAD

**Issue by pure6688** [Dfam-consortium/RepeatModeler#242]
When using RepeatModeler2.0.5 to analyze the genome, we encountered a RECON error in ROUND5: ERROR from search engine (0)  The RECON version is 1.08 But it doesn 't give specific information about the error, so I can 't solve it. Here is the error code:

Number of families returned by RECON: 59085
Processing families with greater than 15 elements
Instance Gathering: 00:00:08 (hh:mm:ss) Elapsed Time
Refining 344 families

ERROR from search engine (0) 

ERROR from search engine (0) 
Family Refinement: 00:29:33 (hh:mm:ss) Elapsed Time
Round Time: 16:15:54 (hh:mm:ss) Elapsed Time : 286 families discovered.

RepeatScout/RECON discovery complete: 576 families found

**Comment by rmhubley** [comment]
Sorry for the delay....we are a bit short staffed.  In case this is useful in the future. This error comes from RMBlast and could be due to limited memory, a problem with the program binary (e.g. not compatible with the system), or rarely an unknown bug.  In these cases RMBlast probably wrote a file of the form "ncResults-1717693025-928291-4581.18367278532.err" to the filesystem in the temporary working directory ( of the form "RM_927755.ThuJun60957032024/" ) or one of its subdirectories.  In a case like this it's helpful to look for any non-empty files ending in "*.err" in this directory and look inside for more details about what happened.

**Comment by pure6688** [comment]
I downgraded RMBlast to 14.0 and it works fine. Thank you.

**Comment by rmhubley** [comment]
I am not sure why you needed to downgrade, although there are minor differences between 2.14.0 and 2.14.1 so it shouldn't impact your results.  I would recommend compiling rmblast 2.14.1 from source on your system and trying again at some point.
